name: HyperWarned
main: HyperWarned\Main
version: 1.0.0
api: [1.13.0]

load: POSTWORLD
authors: [HyperCraftTeam]
description: Warn them rule-breakers!

commands:
    warn:
        description: "Warn a player!"
        usage: "/warn <player> [reason]"
        permission: warnme.warn
permissions:
    warnme.warn:
        description: "Allows players to warn others"
        default: op
